model:
  categories:
    name:
      maximum: 50
    description:
      maximum: 150
  words:
    name:
      maximum: 50
    meaning:
      maximum: 200

image_format: "image/jpeg,image/gif,image/png"
image_size: [250, 250]
answers: 4
rows: 15
